### ISSUE TITLE
How to use Trex(package manager) to install validasaur

### ISSUE THREAD

**Issue by esmadrider** [emsifa/validasaur#9]
Validasaur is already registered in Deno X. But the Trex only tracks the `mod.ts` in the repo root.

Validasaur's `mod.ts` is in src but not in the root folder.

I don't know is it better to let `mod.ts` in the root folder so I can easily install?

And also, I don't know how to install validasaur in Trex for now.

*Review*: use Trex install directly got 404 error:

```
$ ~/.deno/bin/Trex install --map validasaur
cache package... 
Download https://deno.land/x/validasaur/mod.ts
error: Import 'https://deno.land/x/validasaur/mod.ts' failed: 404 Not Found
error: Uncaught something be wrong
maybe this package not have mod.ts file, use custom install.
Trex --custom module=moduleUrl
```

Thx for reading and waiting for your reply!

**Comment by emsifa** [comment]
I just installed Trex, at this time you can use:

```
Trex i --pkg emsifa/validasaur/src/mod.ts validasaur
```

But I'm open for the new standard. I think I'm gonna move `mod.ts` into root directory very soon.
